### PR TITLE
XKCD

### PR DESCRIPTION
**Pull request by Strikingwolf**
Do I need to explain :P

### CODE REVIEW

**Comment by satanicsanta** [comment]
There is a single flaw, in that the opening bracket is not a new line. http://xkcd.com/221/

**Comment by UndeadZeratul** [comment]
I think you should add the hover text as javadoc.

**Comment by Strikingwolf** [comment]
@UndeadZeratul that would not be in the spirit of the original random number generator

**Comment by nevercast** [comment]
Heh heh heh, I remember that old TextureUtils easter egg.

**Comment by nevercast** [comment]
Thanks, but I think it's better that it remains subtle like it is now :)

**Pull request closed without merging**
